server:
  port: 9000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        # System Service Routes Begin
        - id: TEST-SERVICE
          order: 1
          uri: lb://mdm-service
          predicates:
            - Path=/test-service/**
          filters:
            - RewritePath=/api/test-service/(?<segment>.*).json, /test-service/$\{segment}
            - name: Retry
              args:
                retries: 3
                series:
                  - SERVER_ERROR
                methods:
                  - DELETE
                  - PUT
                  - GET
                  - POST
                exceptions:
                  - java.io.IOException
              # System Service Routes End
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8005/eureka/
